name: Check Pull Request Head Ref

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  check-head-ref:
    runs-on: ubuntu-latest

    steps:
      - name: Output Event Information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Pull Request Head Ref: ${{ github.event.pull_request.head.ref }}"
          elif [ -n "${{ github.event.issue.pull_request }}" ]; then
            echo "Issue is linked to a Pull Request"
            echo "Pull Request Head Ref: ${{ github.event.pull_request.head.ref }}"
          else
            echo "No Pull Request head ref available"
          fi

