name: Trigger Workflows via Comment or Dispatch

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
      comment:
        description: 'Comment to trigger the workflow'
        required: true
      head_ref:
        description: 'Branch reference (head ref)'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Determine Comment Source
        id: comment-source
        uses: actions/github-script@v6
        with:
          script: |
            let comment, pr_number, head_ref;
            
            if (context.eventName === 'workflow_dispatch') {
              // Use inputs from the workflow dispatch
              comment = context.payload.inputs.comment;
              pr_number = context.payload.inputs.pr_number;
              head_ref = context.payload.inputs.head_ref;
            
            } else if (context.eventName === 'issue_comment' && context.payload.issue.pull_request) {
              // Fetch the PR details using the API
              const prData = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number
              });
              comment = context.payload.comment.body;
              pr_number = context.issue.number;
              head_ref = prData.data.head.ref;
            
            } else {
              // Handle the error case
              core.setFailed("No valid pull request context found.");
              return;
            }
            
            // Export the variables to the environment
            core.exportVariable('comment', comment);
            core.exportVariable('pr_number', pr_number);
            core.exportVariable('head_ref', head_ref);
            
            console.log(`Comment: ${comment}`);
            console.log(`PR Number: ${pr_number}`);
            console.log(`Head Ref: ${head_ref}`);



      - name: Echo Comment, PR Number, and Head Ref
        run: |
          echo "Comment: ${{ env.comment }}"
          echo "PR Number: ${{ env.pr_number }}"
          echo "Head Ref: ${{ env.head_ref }}"
