name: Check Pull Request Head Ref

on:
  issue_comment:
    types: [created]

jobs:
  check-head-ref:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Pull Request Information
        if: ${{ github.event.issue.pull_request }}
        uses: actions/github-script@v6
        id: fetch-pr
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            console.log("Pull Request Head Ref:", pr.data.head.ref);
            return { head_ref: pr.data.head.ref };

      - name: Output Pull Request Head Ref
        run: |
          echo "Pull Request Head Ref: ${{ steps.fetch-pr.outputs.head_ref }}"

